/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.co.bluedust.model.DestinyQuestsDestinyObjectiveProgress;

/**
 * Data regarding the progress of a Quest for a specific character. Quests are composed of multiple steps, each with potentially multiple objectives: this QuestStatus will return Objective data for the *currently active* step in this quest.
 */
@ApiModel(description = "Data regarding the progress of a Quest for a specific character. Quests are composed of multiple steps, each with potentially multiple objectives: this QuestStatus will return Objective data for the *currently active* step in this quest.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T23:34:27.728Z")
public class DestinyQuestsDestinyQuestStatus {
  @JsonProperty("questHash")
  private Long questHash = null;

  @JsonProperty("stepHash")
  private Long stepHash = null;

  @JsonProperty("stepObjectives")
  private List<DestinyQuestsDestinyObjectiveProgress> stepObjectives = null;

  @JsonProperty("tracked")
  private Boolean tracked = null;

  @JsonProperty("itemInstanceId")
  private Long itemInstanceId = null;

  @JsonProperty("completed")
  private Boolean completed = null;

  @JsonProperty("redeemed")
  private Boolean redeemed = null;

  @JsonProperty("started")
  private Boolean started = null;

  @JsonProperty("vendorHash")
  private Long vendorHash = null;

  public DestinyQuestsDestinyQuestStatus questHash(Long questHash) {
    this.questHash = questHash;
    return this;
  }

   /**
   * The hash identifier for the Quest Item. (Note: Quests are defined as Items, and thus you would use this to look up the quest&#39;s DestinyInventoryItemDefinition). For information on all steps in the quest, you can then examine its DestinyInventoryItemDefinition.setData property for Quest Steps (which are *also* items). You can use the Item Definition to display human readable data about the overall quest.
   * @return questHash
  **/
  @ApiModelProperty(value = "The hash identifier for the Quest Item. (Note: Quests are defined as Items, and thus you would use this to look up the quest's DestinyInventoryItemDefinition). For information on all steps in the quest, you can then examine its DestinyInventoryItemDefinition.setData property for Quest Steps (which are *also* items). You can use the Item Definition to display human readable data about the overall quest.")
  public Long getQuestHash() {
    return questHash;
  }

  public void setQuestHash(Long questHash) {
    this.questHash = questHash;
  }

  public DestinyQuestsDestinyQuestStatus stepHash(Long stepHash) {
    this.stepHash = stepHash;
    return this;
  }

   /**
   * The hash identifier of the current Quest Step, which is also a DestinyInventoryItemDefinition. You can use this to get human readable data about the current step and what to do in that step.
   * @return stepHash
  **/
  @ApiModelProperty(value = "The hash identifier of the current Quest Step, which is also a DestinyInventoryItemDefinition. You can use this to get human readable data about the current step and what to do in that step.")
  public Long getStepHash() {
    return stepHash;
  }

  public void setStepHash(Long stepHash) {
    this.stepHash = stepHash;
  }

  public DestinyQuestsDestinyQuestStatus stepObjectives(List<DestinyQuestsDestinyObjectiveProgress> stepObjectives) {
    this.stepObjectives = stepObjectives;
    return this;
  }

  public DestinyQuestsDestinyQuestStatus addStepObjectivesItem(DestinyQuestsDestinyObjectiveProgress stepObjectivesItem) {
    if (this.stepObjectives == null) {
      this.stepObjectives = new ArrayList<>();
    }
    this.stepObjectives.add(stepObjectivesItem);
    return this;
  }

   /**
   * A step can have multiple objectives. This will give you the progress for each objective in the current step, in the order in which they are rendered in-game.
   * @return stepObjectives
  **/
  @ApiModelProperty(value = "A step can have multiple objectives. This will give you the progress for each objective in the current step, in the order in which they are rendered in-game.")
  public List<DestinyQuestsDestinyObjectiveProgress> getStepObjectives() {
    return stepObjectives;
  }

  public void setStepObjectives(List<DestinyQuestsDestinyObjectiveProgress> stepObjectives) {
    this.stepObjectives = stepObjectives;
  }

  public DestinyQuestsDestinyQuestStatus tracked(Boolean tracked) {
    this.tracked = tracked;
    return this;
  }

   /**
   * Whether or not the quest is tracked
   * @return tracked
  **/
  @ApiModelProperty(value = "Whether or not the quest is tracked")
  public Boolean isTracked() {
    return tracked;
  }

  public void setTracked(Boolean tracked) {
    this.tracked = tracked;
  }

  public DestinyQuestsDestinyQuestStatus itemInstanceId(Long itemInstanceId) {
    this.itemInstanceId = itemInstanceId;
    return this;
  }

   /**
   * The current Quest Step will be an instanced item in the player&#39;s inventory. If you care about that, this is the instance ID of that item.
   * @return itemInstanceId
  **/
  @ApiModelProperty(value = "The current Quest Step will be an instanced item in the player's inventory. If you care about that, this is the instance ID of that item.")
  public Long getItemInstanceId() {
    return itemInstanceId;
  }

  public void setItemInstanceId(Long itemInstanceId) {
    this.itemInstanceId = itemInstanceId;
  }

  public DestinyQuestsDestinyQuestStatus completed(Boolean completed) {
    this.completed = completed;
    return this;
  }

   /**
   * Whether or not the whole quest has been completed, regardless of whether or not you have redeemed the rewards for the quest.
   * @return completed
  **/
  @ApiModelProperty(value = "Whether or not the whole quest has been completed, regardless of whether or not you have redeemed the rewards for the quest.")
  public Boolean isCompleted() {
    return completed;
  }

  public void setCompleted(Boolean completed) {
    this.completed = completed;
  }

  public DestinyQuestsDestinyQuestStatus redeemed(Boolean redeemed) {
    this.redeemed = redeemed;
    return this;
  }

   /**
   * Whether or not you have redeemed rewards for this quest.
   * @return redeemed
  **/
  @ApiModelProperty(value = "Whether or not you have redeemed rewards for this quest.")
  public Boolean isRedeemed() {
    return redeemed;
  }

  public void setRedeemed(Boolean redeemed) {
    this.redeemed = redeemed;
  }

  public DestinyQuestsDestinyQuestStatus started(Boolean started) {
    this.started = started;
    return this;
  }

   /**
   * Whether or not you have started this quest.
   * @return started
  **/
  @ApiModelProperty(value = "Whether or not you have started this quest.")
  public Boolean isStarted() {
    return started;
  }

  public void setStarted(Boolean started) {
    this.started = started;
  }

  public DestinyQuestsDestinyQuestStatus vendorHash(Long vendorHash) {
    this.vendorHash = vendorHash;
    return this;
  }

   /**
   * If the quest has a related Vendor that you should talk to in order to initiate the quest/earn rewards/continue the quest, this will be the hash identifier of that Vendor. Look it up its DestinyVendorDefinition.
   * @return vendorHash
  **/
  @ApiModelProperty(value = "If the quest has a related Vendor that you should talk to in order to initiate the quest/earn rewards/continue the quest, this will be the hash identifier of that Vendor. Look it up its DestinyVendorDefinition.")
  public Long getVendorHash() {
    return vendorHash;
  }

  public void setVendorHash(Long vendorHash) {
    this.vendorHash = vendorHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyQuestsDestinyQuestStatus destinyQuestsDestinyQuestStatus = (DestinyQuestsDestinyQuestStatus) o;
    return Objects.equals(this.questHash, destinyQuestsDestinyQuestStatus.questHash) &&
        Objects.equals(this.stepHash, destinyQuestsDestinyQuestStatus.stepHash) &&
        Objects.equals(this.stepObjectives, destinyQuestsDestinyQuestStatus.stepObjectives) &&
        Objects.equals(this.tracked, destinyQuestsDestinyQuestStatus.tracked) &&
        Objects.equals(this.itemInstanceId, destinyQuestsDestinyQuestStatus.itemInstanceId) &&
        Objects.equals(this.completed, destinyQuestsDestinyQuestStatus.completed) &&
        Objects.equals(this.redeemed, destinyQuestsDestinyQuestStatus.redeemed) &&
        Objects.equals(this.started, destinyQuestsDestinyQuestStatus.started) &&
        Objects.equals(this.vendorHash, destinyQuestsDestinyQuestStatus.vendorHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(questHash, stepHash, stepObjectives, tracked, itemInstanceId, completed, redeemed, started, vendorHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyQuestsDestinyQuestStatus {\n");
    
    sb.append("    questHash: ").append(toIndentedString(questHash)).append("\n");
    sb.append("    stepHash: ").append(toIndentedString(stepHash)).append("\n");
    sb.append("    stepObjectives: ").append(toIndentedString(stepObjectives)).append("\n");
    sb.append("    tracked: ").append(toIndentedString(tracked)).append("\n");
    sb.append("    itemInstanceId: ").append(toIndentedString(itemInstanceId)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    redeemed: ").append(toIndentedString(redeemed)).append("\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    vendorHash: ").append(toIndentedString(vendorHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

