/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.co.bluedust.model.DestinyResponsesDestinyErrorProfile;
import uk.co.bluedust.model.UserUserInfoCard;

/**
 * I know what you seek. You seek linked accounts. Found them, you have.  This contract returns a minimal amount of data about Destiny Accounts that are linked through your Bungie.Net account. We will not return accounts in this response whose
 */
@ApiModel(description = "I know what you seek. You seek linked accounts. Found them, you have.  This contract returns a minimal amount of data about Destiny Accounts that are linked through your Bungie.Net account. We will not return accounts in this response whose")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-08T21:00:47.497Z")
public class DestinyResponsesDestinyLinkedProfilesResponse {
  @JsonProperty("profiles")
  private List<UserUserInfoCard> profiles = null;

  @JsonProperty("bnetMembership")
  private Object bnetMembership = null;

  @JsonProperty("profilesWithErrors")
  private List<DestinyResponsesDestinyErrorProfile> profilesWithErrors = null;

  public DestinyResponsesDestinyLinkedProfilesResponse profiles(List<UserUserInfoCard> profiles) {
    this.profiles = profiles;
    return this;
  }

  public DestinyResponsesDestinyLinkedProfilesResponse addProfilesItem(UserUserInfoCard profilesItem) {
    if (this.profiles == null) {
      this.profiles = new ArrayList<>();
    }
    this.profiles.add(profilesItem);
    return this;
  }

   /**
   * Any Destiny account for whom we could successfully pull characters will be returned here, as the Platform-level summary of user data. (no character data, no Destiny account data other than the Membership ID and Type so you can make further queries)
   * @return profiles
  **/
  @ApiModelProperty(value = "Any Destiny account for whom we could successfully pull characters will be returned here, as the Platform-level summary of user data. (no character data, no Destiny account data other than the Membership ID and Type so you can make further queries)")
  public List<UserUserInfoCard> getProfiles() {
    return profiles;
  }

  public void setProfiles(List<UserUserInfoCard> profiles) {
    this.profiles = profiles;
  }

  public DestinyResponsesDestinyLinkedProfilesResponse bnetMembership(Object bnetMembership) {
    this.bnetMembership = bnetMembership;
    return this;
  }

   /**
   * If the requested membership had a linked Bungie.Net membership ID, this is the basic information about that BNet account.  I know, Tetron; I know this is mixing UserServices concerns with DestinyServices concerns. But it&#39;s so damn convenient! https://www.youtube.com/watch?v&#x3D;X5R-bB-gKVI
   * @return bnetMembership
  **/
  @ApiModelProperty(value = "If the requested membership had a linked Bungie.Net membership ID, this is the basic information about that BNet account.  I know, Tetron; I know this is mixing UserServices concerns with DestinyServices concerns. But it's so damn convenient! https://www.youtube.com/watch?v=X5R-bB-gKVI")
  public Object getBnetMembership() {
    return bnetMembership;
  }

  public void setBnetMembership(Object bnetMembership) {
    this.bnetMembership = bnetMembership;
  }

  public DestinyResponsesDestinyLinkedProfilesResponse profilesWithErrors(List<DestinyResponsesDestinyErrorProfile> profilesWithErrors) {
    this.profilesWithErrors = profilesWithErrors;
    return this;
  }

  public DestinyResponsesDestinyLinkedProfilesResponse addProfilesWithErrorsItem(DestinyResponsesDestinyErrorProfile profilesWithErrorsItem) {
    if (this.profilesWithErrors == null) {
      this.profilesWithErrors = new ArrayList<>();
    }
    this.profilesWithErrors.add(profilesWithErrorsItem);
    return this;
  }

   /**
   * This is brief summary info for profiles that we believe have valid Destiny info, but who failed to return data for some other reason and thus we know that subsequent calls for their info will also fail.
   * @return profilesWithErrors
  **/
  @ApiModelProperty(value = "This is brief summary info for profiles that we believe have valid Destiny info, but who failed to return data for some other reason and thus we know that subsequent calls for their info will also fail.")
  public List<DestinyResponsesDestinyErrorProfile> getProfilesWithErrors() {
    return profilesWithErrors;
  }

  public void setProfilesWithErrors(List<DestinyResponsesDestinyErrorProfile> profilesWithErrors) {
    this.profilesWithErrors = profilesWithErrors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyResponsesDestinyLinkedProfilesResponse destinyResponsesDestinyLinkedProfilesResponse = (DestinyResponsesDestinyLinkedProfilesResponse) o;
    return Objects.equals(this.profiles, destinyResponsesDestinyLinkedProfilesResponse.profiles) &&
        Objects.equals(this.bnetMembership, destinyResponsesDestinyLinkedProfilesResponse.bnetMembership) &&
        Objects.equals(this.profilesWithErrors, destinyResponsesDestinyLinkedProfilesResponse.profilesWithErrors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profiles, bnetMembership, profilesWithErrors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyResponsesDestinyLinkedProfilesResponse {\n");
    
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("    bnetMembership: ").append(toIndentedString(bnetMembership)).append("\n");
    sb.append("    profilesWithErrors: ").append(toIndentedString(profilesWithErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

