/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.co.bluedust.model.DestinyDestinyPresentationDisplayStyle;
import uk.co.bluedust.model.DestinyDestinyPresentationNodeType;

/**
 * DestinyDefinitionsPresentationDestinyPresentationChildBlock
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-08T21:00:47.497Z")
public class DestinyDefinitionsPresentationDestinyPresentationChildBlock {
  @JsonProperty("presentationNodeType")
  private DestinyDestinyPresentationNodeType presentationNodeType = null;

  @JsonProperty("parentPresentationNodeHashes")
  private List<Long> parentPresentationNodeHashes = null;

  @JsonProperty("displayStyle")
  private DestinyDestinyPresentationDisplayStyle displayStyle = null;

  public DestinyDefinitionsPresentationDestinyPresentationChildBlock presentationNodeType(DestinyDestinyPresentationNodeType presentationNodeType) {
    this.presentationNodeType = presentationNodeType;
    return this;
  }

   /**
   * Get presentationNodeType
   * @return presentationNodeType
  **/
  @ApiModelProperty(value = "")
  public DestinyDestinyPresentationNodeType getPresentationNodeType() {
    return presentationNodeType;
  }

  public void setPresentationNodeType(DestinyDestinyPresentationNodeType presentationNodeType) {
    this.presentationNodeType = presentationNodeType;
  }

  public DestinyDefinitionsPresentationDestinyPresentationChildBlock parentPresentationNodeHashes(List<Long> parentPresentationNodeHashes) {
    this.parentPresentationNodeHashes = parentPresentationNodeHashes;
    return this;
  }

  public DestinyDefinitionsPresentationDestinyPresentationChildBlock addParentPresentationNodeHashesItem(Long parentPresentationNodeHashesItem) {
    if (this.parentPresentationNodeHashes == null) {
      this.parentPresentationNodeHashes = new ArrayList<>();
    }
    this.parentPresentationNodeHashes.add(parentPresentationNodeHashesItem);
    return this;
  }

   /**
   * Get parentPresentationNodeHashes
   * @return parentPresentationNodeHashes
  **/
  @ApiModelProperty(value = "")
  public List<Long> getParentPresentationNodeHashes() {
    return parentPresentationNodeHashes;
  }

  public void setParentPresentationNodeHashes(List<Long> parentPresentationNodeHashes) {
    this.parentPresentationNodeHashes = parentPresentationNodeHashes;
  }

  public DestinyDefinitionsPresentationDestinyPresentationChildBlock displayStyle(DestinyDestinyPresentationDisplayStyle displayStyle) {
    this.displayStyle = displayStyle;
    return this;
  }

   /**
   * Get displayStyle
   * @return displayStyle
  **/
  @ApiModelProperty(value = "")
  public DestinyDestinyPresentationDisplayStyle getDisplayStyle() {
    return displayStyle;
  }

  public void setDisplayStyle(DestinyDestinyPresentationDisplayStyle displayStyle) {
    this.displayStyle = displayStyle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyDefinitionsPresentationDestinyPresentationChildBlock destinyDefinitionsPresentationDestinyPresentationChildBlock = (DestinyDefinitionsPresentationDestinyPresentationChildBlock) o;
    return Objects.equals(this.presentationNodeType, destinyDefinitionsPresentationDestinyPresentationChildBlock.presentationNodeType) &&
        Objects.equals(this.parentPresentationNodeHashes, destinyDefinitionsPresentationDestinyPresentationChildBlock.parentPresentationNodeHashes) &&
        Objects.equals(this.displayStyle, destinyDefinitionsPresentationDestinyPresentationChildBlock.displayStyle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(presentationNodeType, parentPresentationNodeHashes, displayStyle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyDefinitionsPresentationDestinyPresentationChildBlock {\n");
    
    sb.append("    presentationNodeType: ").append(toIndentedString(presentationNodeType)).append("\n");
    sb.append("    parentPresentationNodeHashes: ").append(toIndentedString(parentPresentationNodeHashes)).append("\n");
    sb.append("    displayStyle: ").append(toIndentedString(displayStyle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

