/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DestinyConstantsDestinyEnvironmentLocationMapping
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T16:59:02.979Z")
public class DestinyConstantsDestinyEnvironmentLocationMapping {
  @JsonProperty("locationHash")
  private Integer locationHash = null;

  @JsonProperty("activationSource")
  private String activationSource = null;

  @JsonProperty("itemHash")
  private Integer itemHash = null;

  @JsonProperty("objectiveHash")
  private Integer objectiveHash = null;

  @JsonProperty("activityHash")
  private Integer activityHash = null;

  public DestinyConstantsDestinyEnvironmentLocationMapping locationHash(Integer locationHash) {
    this.locationHash = locationHash;
    return this;
  }

   /**
   * The location that is revealed on the director by this mapping.
   * @return locationHash
  **/
  @ApiModelProperty(value = "The location that is revealed on the director by this mapping.")
  public Integer getLocationHash() {
    return locationHash;
  }

  public void setLocationHash(Integer locationHash) {
    this.locationHash = locationHash;
  }

  public DestinyConstantsDestinyEnvironmentLocationMapping activationSource(String activationSource) {
    this.activationSource = activationSource;
    return this;
  }

   /**
   * A hint that the UI uses to figure out how this location is activated by the player.
   * @return activationSource
  **/
  @ApiModelProperty(value = "A hint that the UI uses to figure out how this location is activated by the player.")
  public String getActivationSource() {
    return activationSource;
  }

  public void setActivationSource(String activationSource) {
    this.activationSource = activationSource;
  }

  public DestinyConstantsDestinyEnvironmentLocationMapping itemHash(Integer itemHash) {
    this.itemHash = itemHash;
    return this;
  }

   /**
   * If this is populated, it is the item that you must possess for this location to be active because of this mapping. (theoretically, a location can have multiple mappings, and some might require an item while others don&#39;t)
   * @return itemHash
  **/
  @ApiModelProperty(value = "If this is populated, it is the item that you must possess for this location to be active because of this mapping. (theoretically, a location can have multiple mappings, and some might require an item while others don't)")
  public Integer getItemHash() {
    return itemHash;
  }

  public void setItemHash(Integer itemHash) {
    this.itemHash = itemHash;
  }

  public DestinyConstantsDestinyEnvironmentLocationMapping objectiveHash(Integer objectiveHash) {
    this.objectiveHash = objectiveHash;
    return this;
  }

   /**
   * If this is populated, this is an objective related to the location.
   * @return objectiveHash
  **/
  @ApiModelProperty(value = "If this is populated, this is an objective related to the location.")
  public Integer getObjectiveHash() {
    return objectiveHash;
  }

  public void setObjectiveHash(Integer objectiveHash) {
    this.objectiveHash = objectiveHash;
  }

  public DestinyConstantsDestinyEnvironmentLocationMapping activityHash(Integer activityHash) {
    this.activityHash = activityHash;
    return this;
  }

   /**
   * If this is populated, this is the activity you have to be playing in order to see this location appear because of this mapping. (theoretically, a location can have multiple mappings, and some might require you to be in a specific activity when others don&#39;t)
   * @return activityHash
  **/
  @ApiModelProperty(value = "If this is populated, this is the activity you have to be playing in order to see this location appear because of this mapping. (theoretically, a location can have multiple mappings, and some might require you to be in a specific activity when others don't)")
  public Integer getActivityHash() {
    return activityHash;
  }

  public void setActivityHash(Integer activityHash) {
    this.activityHash = activityHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyConstantsDestinyEnvironmentLocationMapping destinyConstantsDestinyEnvironmentLocationMapping = (DestinyConstantsDestinyEnvironmentLocationMapping) o;
    return Objects.equals(this.locationHash, destinyConstantsDestinyEnvironmentLocationMapping.locationHash) &&
        Objects.equals(this.activationSource, destinyConstantsDestinyEnvironmentLocationMapping.activationSource) &&
        Objects.equals(this.itemHash, destinyConstantsDestinyEnvironmentLocationMapping.itemHash) &&
        Objects.equals(this.objectiveHash, destinyConstantsDestinyEnvironmentLocationMapping.objectiveHash) &&
        Objects.equals(this.activityHash, destinyConstantsDestinyEnvironmentLocationMapping.activityHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationHash, activationSource, itemHash, objectiveHash, activityHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyConstantsDestinyEnvironmentLocationMapping {\n");
    
    sb.append("    locationHash: ").append(toIndentedString(locationHash)).append("\n");
    sb.append("    activationSource: ").append(toIndentedString(activationSource)).append("\n");
    sb.append("    itemHash: ").append(toIndentedString(itemHash)).append("\n");
    sb.append("    objectiveHash: ").append(toIndentedString(objectiveHash)).append("\n");
    sb.append("    activityHash: ").append(toIndentedString(activityHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

