/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import uk.co.bluedust.model.DestinyHistoricalStatsDestinyHistoricalStatsByPeriod;

/**
 * DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T16:59:02.979Z")
public class DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter {
  @JsonProperty("characterId")
  private Long characterId = null;

  @JsonProperty("deleted")
  private Boolean deleted = null;

  @JsonProperty("results")
  private Map<String, DestinyHistoricalStatsDestinyHistoricalStatsByPeriod> results = null;

  @JsonProperty("merged")
  private DestinyHistoricalStatsDestinyHistoricalStatsByPeriod merged = null;

  public DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter characterId(Long characterId) {
    this.characterId = characterId;
    return this;
  }

   /**
   * Get characterId
   * @return characterId
  **/
  @ApiModelProperty(value = "")
  public Long getCharacterId() {
    return characterId;
  }

  public void setCharacterId(Long characterId) {
    this.characterId = characterId;
  }

  public DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @ApiModelProperty(value = "")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter results(Map<String, DestinyHistoricalStatsDestinyHistoricalStatsByPeriod> results) {
    this.results = results;
    return this;
  }

  public DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter putResultsItem(String key, DestinyHistoricalStatsDestinyHistoricalStatsByPeriod resultsItem) {
    if (this.results == null) {
      this.results = new HashMap<>();
    }
    this.results.put(key, resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @ApiModelProperty(value = "")
  public Map<String, DestinyHistoricalStatsDestinyHistoricalStatsByPeriod> getResults() {
    return results;
  }

  public void setResults(Map<String, DestinyHistoricalStatsDestinyHistoricalStatsByPeriod> results) {
    this.results = results;
  }

  public DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter merged(DestinyHistoricalStatsDestinyHistoricalStatsByPeriod merged) {
    this.merged = merged;
    return this;
  }

   /**
   * Get merged
   * @return merged
  **/
  @ApiModelProperty(value = "")
  public DestinyHistoricalStatsDestinyHistoricalStatsByPeriod getMerged() {
    return merged;
  }

  public void setMerged(DestinyHistoricalStatsDestinyHistoricalStatsByPeriod merged) {
    this.merged = merged;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter destinyHistoricalStatsDestinyHistoricalStatsPerCharacter = (DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter) o;
    return Objects.equals(this.characterId, destinyHistoricalStatsDestinyHistoricalStatsPerCharacter.characterId) &&
        Objects.equals(this.deleted, destinyHistoricalStatsDestinyHistoricalStatsPerCharacter.deleted) &&
        Objects.equals(this.results, destinyHistoricalStatsDestinyHistoricalStatsPerCharacter.results) &&
        Objects.equals(this.merged, destinyHistoricalStatsDestinyHistoricalStatsPerCharacter.merged);
  }

  @Override
  public int hashCode() {
    return Objects.hash(characterId, deleted, results, merged);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyHistoricalStatsDestinyHistoricalStatsPerCharacter {\n");
    
    sb.append("    characterId: ").append(toIndentedString(characterId)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    merged: ").append(toIndentedString(merged)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

