/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T16:59:02.979Z")
public class DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {
  @JsonProperty("currencyItemHash")
  private Integer currencyItemHash = null;

  @JsonProperty("scalarValue")
  private Integer scalarValue = null;

  public DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry currencyItemHash(Integer currencyItemHash) {
    this.currencyItemHash = currencyItemHash;
    return this;
  }

   /**
   * Get currencyItemHash
   * @return currencyItemHash
  **/
  @ApiModelProperty(value = "")
  public Integer getCurrencyItemHash() {
    return currencyItemHash;
  }

  public void setCurrencyItemHash(Integer currencyItemHash) {
    this.currencyItemHash = currencyItemHash;
  }

  public DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry scalarValue(Integer scalarValue) {
    this.scalarValue = scalarValue;
    return this;
  }

   /**
   * Get scalarValue
   * @return scalarValue
  **/
  @ApiModelProperty(value = "")
  public Integer getScalarValue() {
    return scalarValue;
  }

  public void setScalarValue(Integer scalarValue) {
    this.scalarValue = scalarValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry destinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry = (DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry) o;
    return Objects.equals(this.currencyItemHash, destinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry.currencyItemHash) &&
        Objects.equals(this.scalarValue, destinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry.scalarValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencyItemHash, scalarValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyDefinitionsSocketsDestinySocketTypeScalarMaterialRequirementEntry {\n");
    
    sb.append("    currencyItemHash: ").append(toIndentedString(currencyItemHash)).append("\n");
    sb.append("    scalarValue: ").append(toIndentedString(scalarValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

