/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * If a vendor can ever end up performing actions, these are the properties that will be related to those actions. I&#39;m not going to bother documenting this yet, as it is unused and unclear if it will ever be used... but in case it is ever populated and someone finds it useful, it is defined here.
 */
@ApiModel(description = "If a vendor can ever end up performing actions, these are the properties that will be related to those actions. I'm not going to bother documenting this yet, as it is unused and unclear if it will ever be used... but in case it is ever populated and someone finds it useful, it is defined here.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T16:59:02.979Z")
public class DestinyDefinitionsDestinyVendorActionDefinition {
  @JsonProperty("description")
  private String description = null;

  @JsonProperty("executeSeconds")
  private Integer executeSeconds = null;

  @JsonProperty("icon")
  private String icon = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("verb")
  private String verb = null;

  @JsonProperty("isPositive")
  private Boolean isPositive = null;

  @JsonProperty("actionId")
  private String actionId = null;

  @JsonProperty("actionHash")
  private Integer actionHash = null;

  @JsonProperty("autoPerformAction")
  private Boolean autoPerformAction = null;

  public DestinyDefinitionsDestinyVendorActionDefinition description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition executeSeconds(Integer executeSeconds) {
    this.executeSeconds = executeSeconds;
    return this;
  }

   /**
   * Get executeSeconds
   * @return executeSeconds
  **/
  @ApiModelProperty(value = "")
  public Integer getExecuteSeconds() {
    return executeSeconds;
  }

  public void setExecuteSeconds(Integer executeSeconds) {
    this.executeSeconds = executeSeconds;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition icon(String icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon
  **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition verb(String verb) {
    this.verb = verb;
    return this;
  }

   /**
   * Get verb
   * @return verb
  **/
  @ApiModelProperty(value = "")
  public String getVerb() {
    return verb;
  }

  public void setVerb(String verb) {
    this.verb = verb;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition isPositive(Boolean isPositive) {
    this.isPositive = isPositive;
    return this;
  }

   /**
   * Get isPositive
   * @return isPositive
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPositive() {
    return isPositive;
  }

  public void setIsPositive(Boolean isPositive) {
    this.isPositive = isPositive;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition actionId(String actionId) {
    this.actionId = actionId;
    return this;
  }

   /**
   * Get actionId
   * @return actionId
  **/
  @ApiModelProperty(value = "")
  public String getActionId() {
    return actionId;
  }

  public void setActionId(String actionId) {
    this.actionId = actionId;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition actionHash(Integer actionHash) {
    this.actionHash = actionHash;
    return this;
  }

   /**
   * Get actionHash
   * @return actionHash
  **/
  @ApiModelProperty(value = "")
  public Integer getActionHash() {
    return actionHash;
  }

  public void setActionHash(Integer actionHash) {
    this.actionHash = actionHash;
  }

  public DestinyDefinitionsDestinyVendorActionDefinition autoPerformAction(Boolean autoPerformAction) {
    this.autoPerformAction = autoPerformAction;
    return this;
  }

   /**
   * Get autoPerformAction
   * @return autoPerformAction
  **/
  @ApiModelProperty(value = "")
  public Boolean isAutoPerformAction() {
    return autoPerformAction;
  }

  public void setAutoPerformAction(Boolean autoPerformAction) {
    this.autoPerformAction = autoPerformAction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyDefinitionsDestinyVendorActionDefinition destinyDefinitionsDestinyVendorActionDefinition = (DestinyDefinitionsDestinyVendorActionDefinition) o;
    return Objects.equals(this.description, destinyDefinitionsDestinyVendorActionDefinition.description) &&
        Objects.equals(this.executeSeconds, destinyDefinitionsDestinyVendorActionDefinition.executeSeconds) &&
        Objects.equals(this.icon, destinyDefinitionsDestinyVendorActionDefinition.icon) &&
        Objects.equals(this.name, destinyDefinitionsDestinyVendorActionDefinition.name) &&
        Objects.equals(this.verb, destinyDefinitionsDestinyVendorActionDefinition.verb) &&
        Objects.equals(this.isPositive, destinyDefinitionsDestinyVendorActionDefinition.isPositive) &&
        Objects.equals(this.actionId, destinyDefinitionsDestinyVendorActionDefinition.actionId) &&
        Objects.equals(this.actionHash, destinyDefinitionsDestinyVendorActionDefinition.actionHash) &&
        Objects.equals(this.autoPerformAction, destinyDefinitionsDestinyVendorActionDefinition.autoPerformAction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, executeSeconds, icon, name, verb, isPositive, actionId, actionHash, autoPerformAction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyDefinitionsDestinyVendorActionDefinition {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    executeSeconds: ").append(toIndentedString(executeSeconds)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    verb: ").append(toIndentedString(verb)).append("\n");
    sb.append("    isPositive: ").append(toIndentedString(isPositive)).append("\n");
    sb.append("    actionId: ").append(toIndentedString(actionId)).append("\n");
    sb.append("    actionHash: ").append(toIndentedString(actionHash)).append("\n");
    sb.append("    autoPerformAction: ").append(toIndentedString(autoPerformAction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

