/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances
 */
public enum DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances {
  
  NUMBER_0(0),
  
  NUMBER_1(1),
  
  NUMBER_2(2),
  
  NUMBER_4(4),
  
  NUMBER_8(8),
  
  NUMBER_16(16),
  
  NUMBER_32(32),
  
  NUMBER_64(64),
  
  NUMBER_128(128),
  
  NUMBER_256(256),
  
  NUMBER_512(512),
  
  NUMBER_1024(1024),
  
  NUMBER_2048(2048),
  
  NUMBER_4096(4096),
  
  NUMBER_8191(8191);

  private Integer value;

  DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances fromValue(String text) {
    for (DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances b : DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

