/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DestinyAdvancedAwaPermissionRequested
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-29T19:57:25.109+01:00")
public class DestinyAdvancedAwaPermissionRequested {
  @JsonProperty("type")
  private Object type = null;

  @JsonProperty("affectedItemId")
  private Long affectedItemId = null;

  @JsonProperty("membershipType")
  private Object membershipType = null;

  @JsonProperty("characterId")
  private Long characterId = null;

  public DestinyAdvancedAwaPermissionRequested type(Object type) {
    this.type = type;
    return this;
  }

   /**
   * Type of advanced write action.
   * @return type
  **/
  @ApiModelProperty(value = "Type of advanced write action.")
  public Object getType() {
    return type;
  }

  public void setType(Object type) {
    this.type = type;
  }

  public DestinyAdvancedAwaPermissionRequested affectedItemId(Long affectedItemId) {
    this.affectedItemId = affectedItemId;
    return this;
  }

   /**
   * Item instance ID the action shall be applied to. This is optional for all but a new AwaType values. Rule of thumb is to provide the item instance ID if one is available.
   * @return affectedItemId
  **/
  @ApiModelProperty(value = "Item instance ID the action shall be applied to. This is optional for all but a new AwaType values. Rule of thumb is to provide the item instance ID if one is available.")
  public Long getAffectedItemId() {
    return affectedItemId;
  }

  public void setAffectedItemId(Long affectedItemId) {
    this.affectedItemId = affectedItemId;
  }

  public DestinyAdvancedAwaPermissionRequested membershipType(Object membershipType) {
    this.membershipType = membershipType;
    return this;
  }

   /**
   * Destiny membership type of the account to modify.
   * @return membershipType
  **/
  @ApiModelProperty(value = "Destiny membership type of the account to modify.")
  public Object getMembershipType() {
    return membershipType;
  }

  public void setMembershipType(Object membershipType) {
    this.membershipType = membershipType;
  }

  public DestinyAdvancedAwaPermissionRequested characterId(Long characterId) {
    this.characterId = characterId;
    return this;
  }

   /**
   * Destiny character ID, if applicable, that will be affected by the action.
   * @return characterId
  **/
  @ApiModelProperty(value = "Destiny character ID, if applicable, that will be affected by the action.")
  public Long getCharacterId() {
    return characterId;
  }

  public void setCharacterId(Long characterId) {
    this.characterId = characterId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyAdvancedAwaPermissionRequested destinyAdvancedAwaPermissionRequested = (DestinyAdvancedAwaPermissionRequested) o;
    return Objects.equals(this.type, destinyAdvancedAwaPermissionRequested.type) &&
        Objects.equals(this.affectedItemId, destinyAdvancedAwaPermissionRequested.affectedItemId) &&
        Objects.equals(this.membershipType, destinyAdvancedAwaPermissionRequested.membershipType) &&
        Objects.equals(this.characterId, destinyAdvancedAwaPermissionRequested.characterId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, affectedItemId, membershipType, characterId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyAdvancedAwaPermissionRequested {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    affectedItemId: ").append(toIndentedString(affectedItemId)).append("\n");
    sb.append("    membershipType: ").append(toIndentedString(membershipType)).append("\n");
    sb.append("    characterId: ").append(toIndentedString(characterId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

