/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * If the enum value is &gt; 100, it is a \&quot;special\&quot; group that cannot be queried for directly (special cases apply to when they are returned, and are not relevant in general cases)
 */
public enum DestinyHistoricalStatsDefinitionsDestinyStatsGroupType {
  
  NUMBER_0(0),
  
  NUMBER_1(1),
  
  NUMBER_2(2),
  
  NUMBER_3(3),
  
  NUMBER_100(100),
  
  NUMBER_101(101),
  
  NUMBER_102(102),
  
  NUMBER_103(103),
  
  NUMBER_104(104);

  private Integer value;

  DestinyHistoricalStatsDefinitionsDestinyStatsGroupType(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DestinyHistoricalStatsDefinitionsDestinyStatsGroupType fromValue(String text) {
    for (DestinyHistoricalStatsDefinitionsDestinyStatsGroupType b : DestinyHistoricalStatsDefinitionsDestinyStatsGroupType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

