/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * An individual Destiny Entity returned from the entity search.
 */
@ApiModel(description = "An individual Destiny Entity returned from the entity search.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-29T19:57:25.109+01:00")
public class DestinyDefinitionsDestinyEntitySearchResultItem {
  @JsonProperty("hash")
  private Integer hash = null;

  @JsonProperty("entityType")
  private String entityType = null;

  @JsonProperty("displayProperties")
  private Object displayProperties = null;

  @JsonProperty("weight")
  private Double weight = null;

  public DestinyDefinitionsDestinyEntitySearchResultItem hash(Integer hash) {
    this.hash = hash;
    return this;
  }

   /**
   * The hash identifier of the entity. You will use this to look up the DestinyDefinition relevant for the entity found.
   * @return hash
  **/
  @ApiModelProperty(value = "The hash identifier of the entity. You will use this to look up the DestinyDefinition relevant for the entity found.")
  public Integer getHash() {
    return hash;
  }

  public void setHash(Integer hash) {
    this.hash = hash;
  }

  public DestinyDefinitionsDestinyEntitySearchResultItem entityType(String entityType) {
    this.entityType = entityType;
    return this;
  }

   /**
   * The type of entity, returned as a string matching the DestinyDefinition&#39;s contract class name. You&#39;ll have to have your own mapping from class names to actually looking up those definitions in the manifest databases.
   * @return entityType
  **/
  @ApiModelProperty(value = "The type of entity, returned as a string matching the DestinyDefinition's contract class name. You'll have to have your own mapping from class names to actually looking up those definitions in the manifest databases.")
  public String getEntityType() {
    return entityType;
  }

  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }

  public DestinyDefinitionsDestinyEntitySearchResultItem displayProperties(Object displayProperties) {
    this.displayProperties = displayProperties;
    return this;
  }

   /**
   * Basic display properties on the entity, so you don&#39;t have to look up the definition to show basic results for the item.
   * @return displayProperties
  **/
  @ApiModelProperty(value = "Basic display properties on the entity, so you don't have to look up the definition to show basic results for the item.")
  public Object getDisplayProperties() {
    return displayProperties;
  }

  public void setDisplayProperties(Object displayProperties) {
    this.displayProperties = displayProperties;
  }

  public DestinyDefinitionsDestinyEntitySearchResultItem weight(Double weight) {
    this.weight = weight;
    return this;
  }

   /**
   * The ranking value for sorting that we calculated using our relevance formula. This will hopefully get better with time and iteration.
   * @return weight
  **/
  @ApiModelProperty(value = "The ranking value for sorting that we calculated using our relevance formula. This will hopefully get better with time and iteration.")
  public Double getWeight() {
    return weight;
  }

  public void setWeight(Double weight) {
    this.weight = weight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyDefinitionsDestinyEntitySearchResultItem destinyDefinitionsDestinyEntitySearchResultItem = (DestinyDefinitionsDestinyEntitySearchResultItem) o;
    return Objects.equals(this.hash, destinyDefinitionsDestinyEntitySearchResultItem.hash) &&
        Objects.equals(this.entityType, destinyDefinitionsDestinyEntitySearchResultItem.entityType) &&
        Objects.equals(this.displayProperties, destinyDefinitionsDestinyEntitySearchResultItem.displayProperties) &&
        Objects.equals(this.weight, destinyDefinitionsDestinyEntitySearchResultItem.weight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, entityType, displayProperties, weight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyDefinitionsDestinyEntitySearchResultItem {\n");
    
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    displayProperties: ").append(toIndentedString(displayProperties)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

