/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A subclass of DestinyItemQuantity, that provides not just the item and its quantity but also information that BNet can - at some point - use internally to provide more robust runtime information about the item&#39;s qualities.  If you want it, please ask! We&#39;re just out of time to wire it up right now. Or a clever person just may do it with our existing endpoints.
 */
@ApiModel(description = "A subclass of DestinyItemQuantity, that provides not just the item and its quantity but also information that BNet can - at some point - use internally to provide more robust runtime information about the item's qualities.  If you want it, please ask! We're just out of time to wire it up right now. Or a clever person just may do it with our existing endpoints.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T16:50:06.922Z")
public class DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem {
  @JsonProperty("vendorHash")
  private Integer vendorHash = null;

  @JsonProperty("vendorItemIndex")
  private Integer vendorItemIndex = null;

  @JsonProperty("itemHash")
  private Integer itemHash = null;

  @JsonProperty("itemInstanceId")
  private Long itemInstanceId = null;

  @JsonProperty("quantity")
  private Integer quantity = null;

  public DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem vendorHash(Integer vendorHash) {
    this.vendorHash = vendorHash;
    return this;
  }

   /**
   * The quest reward item *may* be associated with a vendor. If so, this is that vendor. Use this hash to look up the DestinyVendorDefinition.
   * @return vendorHash
  **/
  @ApiModelProperty(value = "The quest reward item *may* be associated with a vendor. If so, this is that vendor. Use this hash to look up the DestinyVendorDefinition.")
  public Integer getVendorHash() {
    return vendorHash;
  }

  public void setVendorHash(Integer vendorHash) {
    this.vendorHash = vendorHash;
  }

  public DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem vendorItemIndex(Integer vendorItemIndex) {
    this.vendorItemIndex = vendorItemIndex;
    return this;
  }

   /**
   * The quest reward item *may* be associated with a vendor. If so, this is the index of the item being sold, which we can use at runtime to find instanced item information for the reward item.
   * @return vendorItemIndex
  **/
  @ApiModelProperty(value = "The quest reward item *may* be associated with a vendor. If so, this is the index of the item being sold, which we can use at runtime to find instanced item information for the reward item.")
  public Integer getVendorItemIndex() {
    return vendorItemIndex;
  }

  public void setVendorItemIndex(Integer vendorItemIndex) {
    this.vendorItemIndex = vendorItemIndex;
  }

  public DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem itemHash(Integer itemHash) {
    this.itemHash = itemHash;
    return this;
  }

   /**
   * The hash identifier for the item in question. Use it to look up the item&#39;s DestinyInventoryItemDefinition.
   * @return itemHash
  **/
  @ApiModelProperty(value = "The hash identifier for the item in question. Use it to look up the item's DestinyInventoryItemDefinition.")
  public Integer getItemHash() {
    return itemHash;
  }

  public void setItemHash(Integer itemHash) {
    this.itemHash = itemHash;
  }

  public DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem itemInstanceId(Long itemInstanceId) {
    this.itemInstanceId = itemInstanceId;
    return this;
  }

   /**
   * If this quantity is referring to a specific instance of an item, this will have the item&#39;s instance ID. Normally, this will be null.
   * @return itemInstanceId
  **/
  @ApiModelProperty(value = "If this quantity is referring to a specific instance of an item, this will have the item's instance ID. Normally, this will be null.")
  public Long getItemInstanceId() {
    return itemInstanceId;
  }

  public void setItemInstanceId(Long itemInstanceId) {
    this.itemInstanceId = itemInstanceId;
  }

  public DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * The amount of the item needed/available depending on the context of where DestinyItemQuantity is being used.
   * @return quantity
  **/
  @ApiModelProperty(value = "The amount of the item needed/available depending on the context of where DestinyItemQuantity is being used.")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem destinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem = (DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem) o;
    return Objects.equals(this.vendorHash, destinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.vendorHash) &&
        Objects.equals(this.vendorItemIndex, destinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.vendorItemIndex) &&
        Objects.equals(this.itemHash, destinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.itemHash) &&
        Objects.equals(this.itemInstanceId, destinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.itemInstanceId) &&
        Objects.equals(this.quantity, destinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vendorHash, vendorItemIndex, itemHash, itemInstanceId, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem {\n");
    
    sb.append("    vendorHash: ").append(toIndentedString(vendorHash)).append("\n");
    sb.append("    vendorItemIndex: ").append(toIndentedString(vendorItemIndex)).append("\n");
    sb.append("    itemHash: ").append(toIndentedString(itemHash)).append("\n");
    sb.append("    itemInstanceId: ").append(toIndentedString(itemInstanceId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

