/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import uk.co.bluedust.model.DestinyHistoricalStatsDestinyHistoricalWeaponStats;

/**
 * DestinyHistoricalStatsDestinyHistoricalWeaponStatsData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T23:34:27.728Z")
public class DestinyHistoricalStatsDestinyHistoricalWeaponStatsData {
  @JsonProperty("weapons")
  private List<DestinyHistoricalStatsDestinyHistoricalWeaponStats> weapons = null;

  public DestinyHistoricalStatsDestinyHistoricalWeaponStatsData weapons(List<DestinyHistoricalStatsDestinyHistoricalWeaponStats> weapons) {
    this.weapons = weapons;
    return this;
  }

  public DestinyHistoricalStatsDestinyHistoricalWeaponStatsData addWeaponsItem(DestinyHistoricalStatsDestinyHistoricalWeaponStats weaponsItem) {
    if (this.weapons == null) {
      this.weapons = new ArrayList<>();
    }
    this.weapons.add(weaponsItem);
    return this;
  }

   /**
   * List of weapons and their perspective values.
   * @return weapons
  **/
  @ApiModelProperty(value = "List of weapons and their perspective values.")
  public List<DestinyHistoricalStatsDestinyHistoricalWeaponStats> getWeapons() {
    return weapons;
  }

  public void setWeapons(List<DestinyHistoricalStatsDestinyHistoricalWeaponStats> weapons) {
    this.weapons = weapons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyHistoricalStatsDestinyHistoricalWeaponStatsData destinyHistoricalStatsDestinyHistoricalWeaponStatsData = (DestinyHistoricalStatsDestinyHistoricalWeaponStatsData) o;
    return Objects.equals(this.weapons, destinyHistoricalStatsDestinyHistoricalWeaponStatsData.weapons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weapons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyHistoricalStatsDestinyHistoricalWeaponStatsData {\n");
    
    sb.append("    weapons: ").append(toIndentedString(weapons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

