/*
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.co.bluedust.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-04T23:34:27.728Z")
public class DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {
  @JsonProperty("collectibleHash")
  private Long collectibleHash = null;

  public DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry collectibleHash(Long collectibleHash) {
    this.collectibleHash = collectibleHash;
    return this;
  }

   /**
   * Get collectibleHash
   * @return collectibleHash
  **/
  @ApiModelProperty(value = "")
  public Long getCollectibleHash() {
    return collectibleHash;
  }

  public void setCollectibleHash(Long collectibleHash) {
    this.collectibleHash = collectibleHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry destinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry = (DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry) o;
    return Objects.equals(this.collectibleHash, destinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry.collectibleHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectibleHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {\n");
    
    sb.append("    collectibleHash: ").append(toIndentedString(collectibleHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

